openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/advertiser:
    get:
      summary: ''
      operationId: getApiAdvertiser
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Not Found!'
                properties:
                  error:
                    type: string
                    example: 'Not Found!'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiAdvertiser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/ads:
    get:
      summary: ''
      operationId: getApiAds
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Not Found!'
                properties:
                  error:
                    type: string
                    example: 'Not Found!'
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiAds
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text_content:
                  type: string
                  description: ''
                  example: impedit
                audio_content:
                  type: string
                  description: ''
                  example: sed
                pack_id:
                  type: string
                  description: ''
                  example: qui
              required:
                - pack_id
      security: []
  '/api/ads/{id}':
    get:
      summary: ''
      operationId: getApiAdsId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Not Found!'
                properties:
                  error:
                    type: string
                    example: 'Not Found!'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiAdsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text_content:
                  type: string
                  description: ''
                  example: id
                audio_content:
                  type: string
                  description: ''
                  example: quisquam
                pack_id:
                  type: string
                  description: ''
                  example: id
              required:
                - pack_id
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the ad.'
        example: animi
        required: true
        schema:
          type: string
  /api/payments:
    get:
      summary: ''
      operationId: getApiPayments
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Not Found!'
                properties:
                  error:
                    type: string
                    example: 'Not Found!'
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiPayments
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ad_id:
                  type: string
                  description: ''
                  example: fuga
                payment_method:
                  type: string
                  description: 'Must be one of <code>cc</code>, <code>transfer</code>, or <code>wire</code>.'
                  example: wire
                status:
                  type: string
                  description: 'Must be one of <code>pending</code>, <code>paid</code>, or <code>failed</code>.'
                  example: paid
              required:
                - ad_id
                - payment_method
                - status
      security: []
  '/api/payments/{id}':
    get:
      summary: ''
      operationId: getApiPaymentsId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Not Found!'
                properties:
                  error:
                    type: string
                    example: 'Not Found!'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiPaymentsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payment_method:
                  type: string
                  description: 'Must be one of <code>cc</code>, <code>transfer</code>, or <code>wire</code>.'
                  example: wire
                status:
                  type: string
                  description: 'Must be one of <code>pending</code>, <code>paid</code>, or <code>failed</code>.'
                  example: failed
              required:
                - payment_method
                - status
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the payment.'
        example: et
        required: true
        schema:
          type: string
  /api/packs:
    get:
      summary: ''
      operationId: getApiPacks
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Not Found!'
                properties:
                  error:
                    type: string
                    example: 'Not Found!'
      tags:
        - Endpoints
      security: []
  '/api/packs/{id}':
    get:
      summary: ''
      operationId: getApiPacksId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Not Found!'
                properties:
                  error:
                    type: string
                    example: 'Not Found!'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the pack.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
